SELECT
 PROFILEA,
 PA.NAME AS PROFILEANAME,
 PROFILEB,
 PB.NAME AS PROFILEBNAME,
 INTERSECTCOUNT 
FROM
(
SELECT
	PSL.PROFILEID AS PROFILEA,
	PSR.PROFILEID AS PROFILEB,
	COUNT(1) AS INTERSECTCOUNT
FROM DBO.PROFILESKILS PSL
INNER JOIN DBO.PROFILESKILS PSR ON PSL.SKILID = PSR.SKILID AND PSL.PROFILEID!= PSR.PROFILEID
GROUP BY PSL.PROFILEID, PSR.PROFILEID
) INS
INNER JOIN DBO.PROFILES PA ON INS.PROFILEA = PA.ID
INNER JOIN DBO.PROFILES PB ON INS.PROFILEB = PB.ID
ORDER BY INTERSECTCOUNT DESC