CREATE VIEW V_SOLUTION_EMPLOYEE
AS
SELECT
SE.EMPLOYEEID,
EMP.[NAME] AS EMPLOYEENAME,
SE.SOLUTIONID,
SE.RATESUM,
SE.WEIGHTSUM
FROM DBO.EMPLOYEES EMP
INNER JOIN
(
SELECT
	ER.EMPLOYEEID, 
	SK.SOLUTIONID,
	SUM(ER.WEIGHT) AS WEIGHTSUM,
	SUM(ER.RATE) AS RATESUM
FROM DBO.V_EMPLOYEESRATES ER
INNER JOIN DBO.SOLUTIONSSKILLS SK ON SK.[SKILLID] = ER.SKILLID
GROUP BY SK.SOLUTIONID, ER.EMPLOYEEID
) SE ON EMP.ID = SE.EMPLOYEEID